<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>06c07cae-a449-4340-8994-5e58a566535e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/a/span/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://blue.kumparan.com/uikit-assets/assets/icons/submit-blue-9be20ac804c12c2e9e72791098c014ab.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;Root__RootWrapper-of43gx-0 MDoEx&quot;]/div[1]/div[@class=&quot;PageWrapper__ContainerWrapper-s12e5q4j-0 dgKpqA&quot;]/div[@class=&quot;Containerweb__Container-sc-1pm2230-0 bprRrM&quot;]/div[@class=&quot;PageWrapper__DesktopWrapper-s12e5q4j-2 euSzdc&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 dlZqSf&quot;]/div[@class=&quot;indexweb__RowDiv-sc-78tqc5-3 hBgMRK&quot;]/div[@class=&quot;PageWrapper__ContentColumn-s12e5q4j-3 cvjbo&quot;]/div[@class=&quot;DetailStoryPage__ArticleWrapper-s1p6574r-0 fvqZIu&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 gjmEbL&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 guLykq&quot;]/div[@class=&quot;Cardweb__CardWrapper-spx4z5-0 NuBJv&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 iZGkxk&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 gpsWdY&quot;]/div[1]/div[@class=&quot;View__StyledView-sc-1nce11s-0 khpuDQ&quot;]/div[@class=&quot;indexweb__TRow-sc-78tqc5-0 ttpZO&quot;]/div[@class=&quot;indexweb__TColumn-sc-78tqc5-1 ifDyVo&quot;]/a[@class=&quot;Commentweb__SubmitButton-sc-1dsz7gr-1 khUWGb&quot;]/span[@class=&quot;Iconweb__IconWrapper-wzfrpq-0 iiPaWv&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 guLykq&quot;]/div[@class=&quot;Iconweb__IconContentWrapper-wzfrpq-1 eALcnT&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='content']/div/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/a/span/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tes'])[1]/following::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagikan'])[1]/following::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Komentar dihapus'])[1]/preceding::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <value>//img[contains(@src,'https://blue.kumparan.com/uikit-assets/assets/icons/submit-blue-9be20ac804c12c2e9e72791098c014ab.svg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//a/span/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
