<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hapus</name>
   <tag></tag>
   <elementGuidId>6844da31-c957-4045-b8b9-7a348f533810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div/div[3]/div/div/div/div/div[2]/div/div/div[2]/button[3]/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Textweb__StyledText-sc-2upo8d-0 hxhLjQ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>gray</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hapus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;Root__RootWrapper-of43gx-0 MDoEx&quot;]/div[1]/div[@class=&quot;PageWrapper__ContainerWrapper-s12e5q4j-0 dgKpqA&quot;]/div[@class=&quot;Containerweb__Container-sc-1pm2230-0 bprRrM&quot;]/div[@class=&quot;PageWrapper__DesktopWrapper-s12e5q4j-2 euSzdc&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 dlZqSf&quot;]/div[@class=&quot;indexweb__RowDiv-sc-78tqc5-3 hBgMRK&quot;]/div[@class=&quot;PageWrapper__ContentColumn-s12e5q4j-3 cvjbo&quot;]/div[@class=&quot;DetailStoryPage__ArticleWrapper-s1p6574r-0 fvqZIu&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 gjmEbL&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 guLykq&quot;]/div[@class=&quot;Cardweb__CardWrapper-spx4z5-0 NuBJv&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 iZGkxk&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 iSKuYB&quot;]/div[1]/div[@class=&quot;Commentweb__HighlightedView-sc-1dsz7gr-4 gQSXZ&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 gpsWdY&quot;]/div[@class=&quot;indexweb__TRow-sc-78tqc5-0 ttpZO&quot;]/div[@class=&quot;indexweb__TColumn-sc-78tqc5-1 eoJQnQ&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 caiKLY&quot;]/div[1]/div[@class=&quot;TextBoxweb__StyledTextBox-n41hy7-0 btynfe&quot;]/button[@class=&quot;Buttonweb__ButtonWrapper-sc-1tj31rk-0 enAzTt&quot;]/span[@class=&quot;Buttonweb__ButtonContentContainer-sc-1tj31rk-1 jsCqjh&quot;]/span[@class=&quot;ButtonLabelweb__ButtonTextWrapper-sc-101x4fq-0 dOKIdk&quot;]/span[@class=&quot;Textweb__StyledText-sc-2upo8d-0 hxhLjQ&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='content']/div/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div/div[3]/div/div/div/div/div[2]/div/div/div[2]/button[3]/span/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balas'])[1]/following::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Komentar dihapus'])[1]/preceding::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//button[3]/span/span/span</value>
   </webElementXpaths>
</WebElementEntity>
