<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Keluar</name>
   <tag></tag>
   <elementGuidId>5dc127c5-46eb-4725-bf15-6ec0d8b7c64a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div[3]/div/div/div/div/div/div/div/div/div[5]/div[2]/div/label/div[2]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Textweb__StyledText-sc-2upo8d-0 kJwucG</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>regular</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;Root__RootWrapper-of43gx-0 MDoEx&quot;]/div[1]/div[@class=&quot;PageWrapper__ContainerWrapper-s12e5q4j-0 dgKpqA&quot;]/div[@class=&quot;Containerweb__Container-sc-1pm2230-0 bprRrM&quot;]/div[@class=&quot;PageWrapper__DesktopWrapper-s12e5q4j-2 euSzdc&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 dlZqSf&quot;]/div[@class=&quot;indexweb__RowDiv-sc-78tqc5-3 hBgMRK&quot;]/div[@class=&quot;PageWrapper__ContentColumn-s12e5q4j-3 cvjbo&quot;]/div[1]/div[@class=&quot;Cardweb__CardWrapper-spx4z5-0 NuBJv&quot;]/div[1]/div[@class=&quot;View__StyledView-sc-1nce11s-0 ekoyMK&quot;]/div[@class=&quot;Cardweb__CardWrapper-spx4z5-0 NuBJv&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 eFflwP&quot;]/label[@class=&quot;ListItemweb__Item-sc-1x1jqof-0 ezBswX&quot;]/div[@class=&quot;indexweb__TColumn-sc-78tqc5-1 dDQGEF&quot;]/div[@class=&quot;View__StyledView-sc-1nce11s-0 bIyYvN&quot;]/div[1]/div[@class=&quot;TextBoxweb__StyledTextBox-n41hy7-0 gtQZEd&quot;]/span[@class=&quot;Textweb__StyledText-sc-2upo8d-0 kJwucG&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='content']/div/div/div[3]/div/div/div/div/div/div/div/div/div[5]/div[2]/div/label/div[2]/div/div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temukan teman Facebook'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengikut'])[1]/following::span[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advertisement'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advertisement'])[2]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/div/label/div[2]/div/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
